### ISSUE TITLE
To consider: Should integrate with components too? Or keep separate (through Storybook)?

### ISSUE THREAD

**Issue by leoloso** [youknowriad/blockbook#15]
Hi Riad, I pose an issue to have in consideration.

I could benefit from BlockBook to document my blocks, but I also have components, which live on a special package "components" in my plugin, and which are also published to npm, so they can be accessed by 3rd parties (such as extensions to my plugin). The structure of the plugin is this one:

```bash
my-plugin/
│
├──blocks/
│ ├──block1/
│ ├──block2/
│ └──block3/
│
├──packages/
│ ├──package1/
│ └──package2/
│
└── my-plugin.php
```

I wonder: would it make sense to have BlockBook not be limited to blocks, but be also able to document components? I know that Storybook fulfills that goal, but then:

- Wouldn't it be better to have everything in a single place?
- Components could be complex, composing other components, yet in [Gutenberg's Storybook](https://wordpress.github.io/gutenberg) it seems to be documenting only atomic components. Hence, currently, complex components have nowhere to be documented...
- Complex components can access the data store, so they could benefit from mocking (#3), and maybe other features that you're intending to add to BlockBook. If you implement these features for BlockBook, they won't be available in Storybook, right?

**Comment by youknowriad** [comment]
An interesting question that also came up on twitter. I can see how it can be useful for developers on projects to have these leave in the same place.

One of the suggestions was to build BlockBook as a plugin for Storybook instead of its own thing. That's definitely possible but at the moment, it's not something I want to pursue for several reasons:

 - I think the experience offered by a dedicated tool is better than trying to shove it into Storybook. The design can be different, the sidebar can be optimized differently, a lot of things come by default in Storybook that is not needed here.

 - I think other than the developers on the project, having these on the same book is not a good approach because in general, the target is different. The components are important for npm users using the library being documented or for the developers on that particular project while blocks are important for developers extending the block editor, writing templates for the block editor and also for users just wanting to try the blocks before installing the plugin.

While there's overlap, I think for the moment it's better to have these as separate one is optimized for components, the other for blocks and themes.

**Comment by youknowriad** [comment]
Going to close this for now. Let's see how it evolves first.
